config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/report', to: 'home#report'
  get '/invoice', to: 'home#invoice'
  get '/view_report', to: 'home#view_report'
  get '/download_report', to: 'home#download_report'

  root 'home#index'

  namespace :admin do
    resources :dashboard, only: [:index]
    resources :referrers
    resources :patients do
      member do
        get 'invoice'
      end

      collection do
        get 'search'
        get 'search_by_name_and_phone_number'
        get 'referrer_search'
      end
    end
    resources :transactions, only: [:index] do
      collection do
        get 'calculate_today_income'
        get 'search'
      end
    end
    resources :procedures
    resources :users
    resources :patient_procedures, only: %i[edit update]

    root 'admin#dashboard'
  end
  
  namespace :receptionist do
    resources :dashboard, only: [:index]
    resources :patients do      
      collection do
        get 'search'
        get 'search_by_name_and_phone_number'
        get 'referrer_search'
      end
    end

    resources :referrers
    resources :procedures
    resources :patient_procedures, only: %i[edit update]
    root 'receptionist#dashboard'
  end

  namespace :typist do
    resources :dashboard, only: [:index]
    resources :referrers
    resources :patients do
      member do
        get 'invoice'
      end

      collection do
        get 'search'
        get 'search_by_name_and_phone_number'
        get 'referrer_search'
      end
    end
    resources :procedures
    resources :patient_procedures, only: %i[edit update]

    root 'typist#dashboard'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :find_patient, only: %i[invoice report download_report]
  before_action :find_invoice_procedure, only: %i[report download_report]
  before_action :get_patient_by_case_id_and_patient_id, only: %i[invoice view_report]

  def index; end

  def invoice
    @tests = @patient.patient_procedures
    respond_to do |format|
      format.html
      format.pdf { 
        render template: 'home/invoice', 
               pdf: "#{@patient.name}",
               formats: [:html],
               disposition: :inline,
               layout: 'pdf',
               page_height: '12in',
               page_width: '8in',
               footer:  {   html: {   
                    template:'shared/footer',
                    formats: [:html],
                    layout:  'pdf'
                  }
                }
      }
    end
  end

  def report
    respond_to do |format|
      format.html
      format.pdf {
        render template: 'home/report',
               pdf: "#{@patient.name}",
               formats: [:html],
               disposition: :inline,
               layout: 'pdf',
               page_size: 'Letter',
               footer:  {   html: {   
                            template:'shared/footer',
                            formats: [:html],
                            layout:  'pdf'
                          }
                        }
            }
    end
  end

  def download_report
    respond_to do |format|
      format.pdf {
        render template: 'home/download_report',
          pdf: "#{@patient.name}",
          formats: [:html],
          disposition: :attachment,
          layout: 'pdf',
          page_size: 'Letter',
          footer:  {   
            html: {   
              template:'shared/footer',
              formats: [:html],
              layout:  'pdf'
            }
          }
        }
    end
  end

  def view_report
    @tests = @patient.patient_procedures
    unless @patient.present?
      redirect_to :root
    end
  end

  private

  def find_patient
    @patient = Patient.find(params[:id]) if params[:id].present?
  end

  def get_patient_by_case_id_and_patient_id
    @patient = Patient.find_by_case_id_and_patient_id(params[:case_id], params[:patient_id]) if params[:patient_id].present? && params[:case_id].present?
  end

  def find_invoice_procedure
    @procedure ||= PatientProcedure.find(params[:test_id])
  end
end

app/views/home/download_report.html.erb
<head>
  <%= wicked_pdf_stylesheet_link_tag "admin_pdf" %>
</head>
<div class="main__pdf">
  <div style="position: absolute; left: 0; top: 0; width: 100%; height: 100%; border: 1px solid rede;">
    <div style="position: relative; left: 50px; top: 50px; opacity: 0.1; width: 500px; height: 600px;">
      <div style="position: absolute; top: 60%; left: 35%; transform: translate(-50%, -50%); text-align: center;">
        <p style="font-size: 24px; color: rgba(0, 0, 0, 0.1);">
          <%= image_tag wicked_pdf_asset_base64('logo'), style: "width: 500px; height: 600px; margin: auto 0; object-fit: cover;"%>
        </p>
      </div>
    </div>
  </div>
  <%= render 'shared/without_logo_header', procedure: @procedure, class: 'mt__0 mb__0'%>
  <hr class='mt__0'/>
  <%= render 'home/partials/report_main_content', procedure: @procedure %>
</div>

app/views/home/index.html.erb
<%= render 'home/partials/home' %>
<%= render 'home/partials/about' %>
<%= render 'home/partials/team' %>
<%= render 'home/partials/services' %>
<%= render 'home/partials/report' %>
<%= render 'home/partials/contact' %>
<%= render 'home/partials/footer' %>

app/views/home/invoice.html.erb
<head>
  <%= wicked_pdf_stylesheet_link_tag "pdf" %>
</head>

<div class="main__pdf h__100">
  <%= render 'shared/invoice_header', class: 'mt__0 mb__0'%>
  <hr/>
  <div class='test-list'>
    <table>
      <tr>
        <td class="pl-20"><h3>Test</h3></td>
        <td class="text__center w__30"><h3>Cost</h3></td>
      </tr>
    </table>
    <hr />
    
    <table>
      <% @tests.each do |test| %>
      <tr class='text__start'>
        <td class="pl-12 mb__0 w__auto">
          <h2 class="test__heading mb__0 w__100"><%= test&.procedure&.title&.humanize %></h2>
          <div class="mb__0 mt__0">
            <span>Referrer: <strong class="performed__and__referrer">
              <%= @patient.referrer.nil? ? '' : @patient.referrer.doctor_name&.titleize %>
            </strong></span>
          </div>
        </td>
        <td class="text__center w__10">
          <h4><%= test.get_test_price %></h4>
        </td>
      </tr>
      <% end %>
    </table>
  </div>

  <hr />

  <table class="w__100">
		<tr>
			<td class="w__1"></td>
			<td>
				<h3>Grand Total:</h3>
			</td>
			<td><h2><%= @patient.bill %></h2></td>
		</tr>
	</table>
</div>

app/views/home/report.html.erb
<head>
  <%= wicked_pdf_stylesheet_link_tag "admin_pdf" %>
</head>
<div class="main__pdf">
  <div style="position: absolute; left: 0; top: 0; width: 100%; height: 100%; border: 1px solid rede;">
    <div style="position: relative; left: 50px; top: 50px; opacity: 0.1; width: 500px; height: 600px;">
      <div style="position: absolute; top: 60%; left: 35%; transform: translate(-50%, -50%); text-align: center;">
        <p style="font-size: 24px; color: rgba(0, 0, 0, 0.1);">
          <%= image_tag wicked_pdf_asset_base64('logo'), style: "width: 500px; height: 600px; margin: auto 0; object-fit: cover;"%>
        </p>
      </div>
    </div>
  </div>
  <%= render 'shared/header', procedure: @procedure, class: 'mt__0 mb__0'%>
  <hr class='mt__0'/>
  <%= render 'home/partials/report_main_content', procedure: @procedure %>
</div>

app/views/home/view_report.html.erb
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounceIn" data-wow-offset="50" data-wow-delay="0.3s"><%= @patient&.name&.humanize %> <span> Reports</span></h2>
      </div>
      <div class="col-md-12 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-offset="50" data-wow-delay="0.9s">
        <table class="w-25 p-2">
          <tr>
            <td><strong>FATHER/HUSBAND: </strong></td>
            <td><%=@patient&.father_husband&.humanize%></td>
          </tr>
          <tr>
            <td><strong>AGE: </strong></td>
            <td><%=@patient&.age %> Years</td>
          </tr>
          <tr>
            <td><strong>PHONE NUMBER: </strong></td>
            <td> <%= @patient&.phone_number %></td>
          </tr>
          <tr>
            <td><strong>ADDRESS: </strong></td>
            <td><%=@patient&.address%></td>
          </tr>
          <tr>
            <td><strong>DATE: </strong></td>
            <td><%= @patient&.created_at&.strftime('%d %b %Y %I:%M %p') %></td>
          </tr>
        </table>
        <div class='py-5'>
          <label><strong>Check Invoice</strong></label>
          <%= link_to "Invoice", invoice_path(id: @patient.id, format: :pdf), class: 'btn btn-primary mx-4', target: '_blank' %>
        </div>
      </div>
      <div class="col-md-12 col-sm-6 col-xs-12 wow fadeInRight my-5" data-wow-offset="50" data-wow-delay="0.6s">
        <table class='w-100'>
          <% @tests.each do |test| %>
            <tr class='w-100 '>
              <td class="pl-12 mb__0 w__auto">
                <h5 class="test__heading mb__0 w-100"><%= test&.procedure&.title&.humanize %></h5>
              </td>
              <td>
                <%= link_to "Report", report_path(id: test&.patient_id, test_id: test&.id, format: :pdf), class: test&.done ? "btn btn-primary" : "btn btn-primary disabled", target: '_blank' if test.done %>
              </td>
            </tr>
          <% end %>
        </table>      
      </div>
    </div>
  </div>
</section>