config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/report', to: 'home#report'
  get '/invoice', to: 'home#invoice'
  get '/view_report', to: 'home#view_report'
  get '/download_report', to: 'home#download_report'

  root 'home#index'

  namespace :admin do
    resources :dashboard, only: [:index]
    resources :referrers
    resources :patients do
      member do
        get 'invoice'
      end

      collection do
        get 'search'
        get 'search_by_name_and_phone_number'
        get 'referrer_search'
      end
    end
    resources :transactions, only: [:index] do
      collection do
        get 'calculate_today_income'
        get 'search'
      end
    end
    resources :procedures
    resources :users
    resources :patient_procedures, only: %i[edit update]

    root 'admin#dashboard'
  end
  
  namespace :receptionist do
    resources :dashboard, only: [:index]
    resources :patients do      
      collection do
        get 'search'
        get 'search_by_name_and_phone_number'
        get 'referrer_search'
      end
    end

    resources :referrers
    resources :procedures
    resources :patient_procedures, only: %i[edit update]
    root 'receptionist#dashboard'
  end

  namespace :typist do
    resources :dashboard, only: [:index]
    resources :referrers
    resources :patients do
      member do
        get 'invoice'
      end

      collection do
        get 'search'
        get 'search_by_name_and_phone_number'
        get 'referrer_search'
      end
    end
    resources :procedures
    resources :patient_procedures, only: %i[edit update]

    root 'typist#dashboard'
  end
end

app/views/admin/partials/_header.html.erb
<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar" >
  <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
    <a class="nav-item nav-link px-0 me-xl-4" id='menu-toggle' href="javascript:void(0)">
      <i class="bx bx-menu bx-sm"></i>
    </a>
  </div>

  <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
    <ul class="navbar-nav flex-row align-items-center ms-auto">
      <li class="nav-item navbar-dropdown dropdown-user dropdown">
        <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
          <div class="avatar avatar-online">
            <%= image_tag('male.jpg', class: "w-px-40 h-auto rounded-circle")%>
          </div>
        </a>
        <ul class="dropdown-menu dropdown-menu-end">
          <li>
            <a class="dropdown-item" href="#">
              <div class="d-flex">
                <div class="flex-shrink-0 me-3">
                  <div class="avatar avatar-online">
                    <%= image_tag('male.jpg', class: "w-px-40 h-auto rounded-circle")%>
                  </div>
                </div>
                <div class="flex-grow-1">
                  <span class="fw-semibold d-block"><%= current_user&.name&.titleize %></span>
                  <small class="text-muted"><%= current_user&.role&.titleize %></small>
                </div>
              </div>
            </a>
          </li>
          <li>
            <div class="dropdown-divider"></div>
          </li>
          <li>
            <a class="dropdown-item" href="#">
              <i class="bx bx-cog me-2"></i>
              <span class="align-middle">Settings</span>
            </a>
          </li>
          <li>
            <div class="dropdown-divider"></div>
          </li>
          <li>
            <div class='dropdown-item'>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="bx bx-power-off me-2">Log Out</i>
              <% end %>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/admin/partials/_sidebar.html.erb
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme inverce-sidebar-menu">
  <div class="m-auto my-3">
    <%= image_tag ('logo'), width: 100, height: 100, class: '' %>
  </div>
  <div class="menu-inner-shadow"></div>
  <ul class="menu-inner py-1">
    <li class="menu-item <%= 'active' if params[:controller] == "admin/dashboard" %>">
      <%= link_to admin_dashboard_index_path, class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-home-circle"></i>
        <div data-i18n="Analytics">Dashboard</div>
      <% end %>
    </li>
    <li class="menu-item <%= 'active' if params[:controller] == "admin/patients" %>">
      <%= link_to admin_patients_path, class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-home-circle"></i>
        <div data-i18n="Analytics">Patients</div>
      <% end %>
    </li>
    <li class="menu-item <%= 'active' if params[:controller] == "admin/procedures" %>">
      <%= link_to admin_procedures_path, class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-home-circle"></i>
        <div data-i18n="Analytics">Procedure</div>
      <% end %>
    </li>
    <li class="menu-item <%= 'active' if params[:controller] == "admin/referrers" %>">
      <%= link_to admin_referrers_path, class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-home-circle"></i>
        <div data-i18n="Analytics">Referrers</div>
      <% end %>
    </li>
    <li class="menu-item <%= 'active' if params[:controller] == "admin/users" %>">
      <%= link_to admin_users_path, class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-home-circle"></i>
        <div data-i18n="Analytics">Users</div>
      <% end %>
    </li>
    <li class="menu-item <%= 'active' if params[:controller] == "admin/transaction" %>">
      <%= link_to admin_transactions_path, class: "menu-link" do %>
        <i class="menu-icon tf-icons bx bx-home-circle"></i>
        <div data-i18n="Analytics">Transaction</div>
      <% end %>
    </li>
  </ul>
</aside>