config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/report', to: 'home#report'
  get '/invoice', to: 'home#invoice'
  get '/view_report', to: 'home#view_report'
  get '/download_report', to: 'home#download_report'

  root 'home#index'

  namespace :admin do
    resources :dashboard, only: [:index]
    resources :referrers
    resources :patients do
      member do
        get 'invoice'
      end

      collection do
        get 'search'
        get 'search_by_name_and_phone_number'
        get 'referrer_search'
      end
    end
    resources :transactions, only: [:index] do
      collection do
        get 'calculate_today_income'
        get 'search'
      end
    end
    resources :procedures
    resources :users
    resources :patient_procedures, only: %i[edit update]

    root 'admin#dashboard'
  end
  
  namespace :receptionist do
    resources :dashboard, only: [:index]
    resources :patients do      
      collection do
        get 'search'
        get 'search_by_name_and_phone_number'
        get 'referrer_search'
      end
    end

    resources :referrers
    resources :procedures
    resources :patient_procedures, only: %i[edit update]
    root 'receptionist#dashboard'
  end

  namespace :typist do
    resources :dashboard, only: [:index]
    resources :referrers
    resources :patients do
      member do
        get 'invoice'
      end

      collection do
        get 'search'
        get 'search_by_name_and_phone_number'
        get 'referrer_search'
      end
    end
    resources :procedures
    resources :patient_procedures, only: %i[edit update]

    root 'typist#dashboard'
  end
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < Admin::BaseController

  def index
    @transactions = Transaction.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  def calculate_today_income
    @transaction   = Transaction.find_by('DATE(created_at) = ?', DateTime.now)

    if @transaction.present?
      @transaction.update(transaction_params)
    else
      @transaction = Transaction.create(transaction_params)
    end
  end

  def search
    start_date = params[:search][:start_date].to_date
    end_date   = params[:search][:end_date].present? ? params[:search][:end_date].to_date : Date.today
    @transactions = Transaction.where(transaction_date: start_date..end_date)
    @total_amount = @transactions.sum(:amount)
  end


  private

  def transaction_params
    {
      amount: Transaction.today_income,
      transaction_date: Date.today
    }
  end
end

app/views/admin/transactions/calculate_today_income.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <div class="card">
    <span class='d-flex align-items-center'>
      <h5 class="card-header">Amount:</h5>
      <p class="card-header"><%= @transaction.amount.to_f %></p>
    </span>

    <span class='d-flex align-items-center'>
      <h5 class="card-header">Date:</h5>
      <p class="card-header"><%= @transaction.transaction_date %></p>
    </span>
  </div>
</div>

app/views/admin/transactions/index.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <button type="button" class="btn p-0 m-3">
    <%= link_to 'Today Income', calculate_today_income_admin_transactions_path, class: 'btn btn-primary'%>
  </button>
  <div class="row">
    <div class="col-md-12">
      <div class="card mb-4">
        <h5 class="card-header">Search Income From Start Date To End Date</h5>
        <div class="card-body demo-vertical-spacing demo-only-element">
          <%= form_for :search, url: search_admin_transactions_path, method: :get do |f| %>
            <div class="row">
              <div class='col-md-4'>
                <%= f.date_field :start_date, placeholder: "Starting Date", required: true, class: 'form-control' %>
              </div>
              <div class='col-md-4'>
                <%= f.date_field :end_date, placeholder: "Ending Date", class: 'form-control' %>
              </div>
              <div class="col-md-3">
                <%= f.submit 'Search Patient', class: 'btn btn-success'%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <% if @transactions.present? %>
      <h5 class="card-header">Income Logs</h5>
      <div class="table-responsive text-nowrap">
        <table class="table">
          <thead>
            <tr>
              <th>Income</th>
              <th>date</th>
            </tr>
          </thead>
          <tbody class="table-border-bottom-0">
            <% @transactions&.each do |transaction| %>
              <tr>
                <td>
                  <strong><%= transaction&.amount %></strong>
                </td>
                <td>
                  <span class="me-1"><%= transaction&.transaction_date %></span>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <%= render 'shared/pagination', instance: @transactions %>
    <% else %>
      <h2 class="card-header">There is No Income yet.</h2>
    <% end %>
  </div>
</div>

app/views/admin/transactions/search.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <div class="card">
    <span class='d-flex align-items-center'>
      <h5 class="card-header">Total Amount:</h5>
      <p class="card-header"><%= @total_amount %></p>
    </span>

    <div class="card">
      <% if @transactions.present? %>
        <h5 class="card-header">Income Logs</h5>
        <div class="table-responsive text-nowrap">
          <table class="table">
            <thead>
              <tr>
                <th>Income</th>
                <th>date</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">
              <% @transactions&.each do |transaction| %>
                <tr>
                  <td>
                    <strong><%= transaction&.amount %></strong>
                  </td>
                  <td>
                    <span class="me-1"><%= transaction&.transaction_date %></span>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>